const memeTemplates = [
    { name: "Middle Finger", value: "1950s-Middle-Finger" },
    { name: "Bitch Please", value: "Bitch-Please" },
    { name: "Computer Guy", value: "Computer-Guy" },
    { name: "Doge", value: "Doge" },
    { name: "Drake", value: "Drake-Bad-Good" },
    { name: "Disaster Girl", value: "Disaster-Girl" },
    { name: "Distracted Boyfriend", value: "Distracted-Boyfriend" },
    { name: "Finding Neverland", value: "Finding-Neverland" },
    { name: "Thinking About Other Women", value: "I-Bet-Hes-Thinking-About-Other-Women" },
    { name: "I Know That Feel Bro", value: "I-Know-That-Feel-Bro" },
    { name: "Kevin Hart", value: "Kevin-Hart" },
    { name: "Monkey Puppet", value: "Monkey-Puppet" },
    { name: "Sad Pablo Escobar", value: "Sad-Pablo-Escobar" },
    { name: "Think", value: "Think" },
    { name: "Troll Face", value: "Troll-Face" },
    { name: "Woman Yelling At Cat", value: "Woman-Yelling-At-Cat" },
    { name: "X Everywhere", value: "X-X-Everywhere" },
    { name: "Two Buttons", value: "Two-Buttons" },
    { name: "Snoop", value: "Snoop" },
    { name: "Patrick Bateman", value: "Patrick-Bateman" },
    { name: "Lol Guy", value: "LOL-Guy" },
    { name: "X is Coming", value: "Brace-Yourselves-X-is-Coming" },
    { name: "Error 404", value: "Error-404" },
    { name: "Gandhi", value: "Gandhi" },
    { name: "Sponegebob Coffee", value: "Sponegebob-Coffee" },
];

module.exports = memeTemplates;